// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANvjPAXgdPunkwq99cIPix_xm7N3zFpdU',
    appId: '1:458108188251:web:1b07f7d5b35e0073f2717e',
    messagingSenderId: '458108188251',
    projectId: 'parking-6f358',
    authDomain: 'parking-6f358.firebaseapp.com',
    storageBucket: 'parking-6f358.appspot.com',
    measurementId: 'G-YXY8QLH3YM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDA9_qSU62gTTpZqO40yNAJIX76XB3jx0',
    appId: '1:458108188251:android:319e21e4de3f791df2717e',
    messagingSenderId: '458108188251',
    projectId: 'parking-6f358',
    storageBucket: 'parking-6f358.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeDhLhM8CF6JULnm45J6FJHEoxWuvsJlU',
    appId: '1:458108188251:ios:fc9f32ce59acebbbf2717e',
    messagingSenderId: '458108188251',
    projectId: 'parking-6f358',
    storageBucket: 'parking-6f358.appspot.com',
    iosClientId:
        '458108188251-6lb1ordniffq3uigmrq9mkju9s4d05l6.apps.googleusercontent.com',
    iosBundleId: 'com.example.parking',
  );
}
